import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.InputStream;
import javax.swing.JOptionPane;
import java.sql.Connection; 
import java.sql.PreparedStatement; 
import java.sql.ResultSet; 
import java.sql.SQLException; 
import java.sql.Statement; 
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JFrame;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Belani
 */
public class UserLogin extends javax.swing.JFrame {

    private SlidePuzzleGame SlidePuzzleGame;
    /**
     * Creates new form UserLogin
     */
    public UserLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LabelLogin = new javax.swing.JLabel();
        PanelLoginDetails = new javax.swing.JPanel();
        LabelName = new javax.swing.JLabel();
        jButtonEnterNewGame = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jTextFieldNameBox = new javax.swing.JTextField();
        jButtonInstructions = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelLogin.setFont(new java.awt.Font("Showcard Gothic", 0, 50)); // NOI18N
        LabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        LabelLogin.setText("slide puzzle login");
        jPanel2.add(LabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 500, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 80));

        PanelLoginDetails.setBackground(new java.awt.Color(51, 51, 51));
        PanelLoginDetails.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        LabelName.setBackground(new java.awt.Color(255, 255, 255));
        LabelName.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        LabelName.setForeground(new java.awt.Color(255, 255, 255));
        LabelName.setText(" User Name :");

        jButtonEnterNewGame.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jButtonEnterNewGame.setText("Enter  New Game");
        jButtonEnterNewGame.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jButtonEnterNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterNewGameActionPerformed(evt);
            }
        });

        jButtonExit.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jTextFieldNameBox.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldNameBox.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jTextFieldNameBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextFieldNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameBoxActionPerformed(evt);
            }
        });

        jButtonInstructions.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jButtonInstructions.setText("Instructions");
        jButtonInstructions.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jButtonInstructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstructionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLoginDetailsLayout = new javax.swing.GroupLayout(PanelLoginDetails);
        PanelLoginDetails.setLayout(PanelLoginDetailsLayout);
        PanelLoginDetailsLayout.setHorizontalGroup(
            PanelLoginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginDetailsLayout.createSequentialGroup()
                .addGroup(PanelLoginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelLoginDetailsLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(LabelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNameBox))
                    .addGroup(PanelLoginDetailsLayout.createSequentialGroup()
                        .addContainerGap(35, Short.MAX_VALUE)
                        .addComponent(jButtonInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(jButtonEnterNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        PanelLoginDetailsLayout.setVerticalGroup(
            PanelLoginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLoginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNameBox)
                    .addComponent(LabelName, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(PanelLoginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLoginDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonEnterNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        getContentPane().add(PanelLoginDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 520, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 610, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private long getBestTime() {
    // Code to get the best player's time from the database
    String sql = "SELECT Time FROM users ORDER BY Time ASC LIMIT 1";

    try (Connection conn = ConnectDB.getConnection();
         Statement stmt = conn.createStatement();
         ResultSet rs = stmt.executeQuery(sql)) {

        if (rs.next()) {
            return rs.getLong("Time");
        }

    } catch (SQLException e) {
        System.out.println(e.getMessage());
    }

    return 0;
}

//*****************************************************************************************************************************************
    
    private void playSoundEffectLogin(String soundEffectFilePath) {
       
        try {
           
           InputStream soundEffectFile = SlidePuzzleGame.class.getClassLoader().getResourceAsStream(soundEffectFilePath);
            
            if (soundEffectFile!= null) {
                
                AudioInputStream soundEffectStream = AudioSystem.getAudioInputStream(new BufferedInputStream(soundEffectFile));
                
                Clip soundEffectClip = AudioSystem.getClip();
                soundEffectClip.open(soundEffectStream);
                soundEffectClip.start();
            } 
            else 
            {
                System.out.println("Sound effect file not found: " + soundEffectFilePath);
            }
        } 
        catch (Exception e) {
            
            System.out.println("Error playing sound effect: " + e.getMessage());
        }
    }    
//*****************************************************************************************************************************************
    
    private void jButtonEnterNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterNewGameActionPerformed
        // TODO add your handling code here:
        playSoundEffectLogin("Wav/bubble-pop.wav");
        
        String userName = jTextFieldNameBox.getText();
    // Check if the user has entered a name
        if(userName.isEmpty()){
 
            ImageIcon LoginNameIcon = new ImageIcon(getClass().getResource("NameImage.png"));
            JOptionPane.showMessageDialog(this, "<html><b style=\"font-size:10px;\">Please enter a user name.","PUZZLE GAME",JOptionPane.INFORMATION_MESSAGE,LoginNameIcon);
        }
        else{
 
            SlidePuzzleGame gameWindow = new SlidePuzzleGame(userName);

    // Make the game window visible
            gameWindow.setVisible(true);
            gameWindow.setEnabled(true);

    // Close the login window
            this.dispose();
        }
    }//GEN-LAST:event_jButtonEnterNewGameActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        playSoundEffectLogin("Wav/bubble-pop.wav");
        
        WindowEvent closeWindow = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jTextFieldNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameBoxActionPerformed

    private void jButtonInstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstructionsActionPerformed
        // TODO add your handling code here:
        playSoundEffectLogin("Wav/bubble-pop.wav");

        ImageIcon WinStateIcon = new ImageIcon(getClass().getResource("WinStateImage.png"));
        String message = "<html><b style=\"font-size:12px; font-family:Arial;  font-style:italic;\">HOW TO PLAY: <br><br>The numbers are initially in random order.<br><br>You have to arrange the tiles in numerical order as this winning state.<br><br>You can move an adjacent tile to the empty space, into the empty space horizontally or vertically.<br><br><br>PLAYING OPTIONS: <br><br>You can solve this puzzle with unlimited time and unlimited moves.<br><br>Also, you can solve the puzzle by selecting options with limited time (10 minutes) or with limited moves (500 moves).<br><br><br><br><br>SO, GOOD LUCK. ROCK ON!</b></html>";
        JOptionPane.showMessageDialog(this,message,"PUZZLE GAME INSTRUCTIONS",JOptionPane.INFORMATION_MESSAGE,WinStateIcon);
       
    }//GEN-LAST:event_jButtonInstructionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JLabel LabelName;
    private javax.swing.JPanel PanelLoginDetails;
    private javax.swing.JButton jButtonEnterNewGame;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonInstructions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldNameBox;
    // End of variables declaration//GEN-END:variables
}
